name: Publish to PyPI

on:
  workflow_dispatch:
    

jobs:
  # Build a pure Python wheel and upload as an artifact
  build-wheel:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies for building the wheel
      run: |
        python -m pip install build

    - name: Create the wheel
      run: python -m build

    - name: Upload the wheel artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: |
          dist/molgroups-*-py3-none-any.whl
          dist/molgroups*.tar.gz

  publish:
    needs: build-wheel
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Retrieve all artifacts
        uses: actions/download-artifact@v4
      
      - name: show files
        run: |
          ls -R artifacts

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: artifacts/
